### ISSUE TITLE
Level Lost

### ISSUE THREAD

**Issue by jooew** [ghostfur/Aion-Lightning-4.9#11]
I was at lv 17 and log out.
Create another char, played more 5 lvls with new char.
Closes aion client and opens again minutes later.

All my chars is at Lvl 1.

Someone knew hot to fix it, please?

PS: Im using windows 7 64bits, and java jdk1.7.0_80 .

Thank you!

**Comment by idhacker542** [comment]
okey thanks to  report , we will update soon

**Comment by YggDrazil** [comment]
The error is due to false entries in the database of the game server. Make a fresh and clean install of the al_server.gs and use the SQL files in the Update folder.

**Comment by noKyrr** [comment]
what mysql storage engine should i use? MYISAM  or INNODB?

**Comment by YggDrazil** [comment]
I use InnoDB
