### ISSUE TITLE
SVN delete a folder

### ISSUE THREAD

**Issue by dev-jet** [ghostfur/Aion-Lightning-4.9#13]
SVN delete a folder, it does not allow to download the source code of the program TortoiseSVN

**Comment by idhacker542** [comment]
try to download only in a folder trunk only

**Comment by dev-jet** [comment]
![default](https://cloud.githubusercontent.com/assets/17547676/16330796/ff42717e-39fc-11e6-8a95-8bcffe9da0ac.jpg)

**Comment by idhacker542** [comment]
goto your folder 
D:\erver_4.9\Aion-Lightning-4.9.git\trunk
then right click , -> tortoiseSVN -> update to reversion
then choose items..
make like this
![untitled](https://cloud.githubusercontent.com/assets/19891294/16356841/cad65dec-3b0f-11e6-8daa-bdd897127e59.png)
